source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Napkin_Example' do
  pod "Napkin", :path => "../"
end

target 'Napkin_Tests' do
  pod "Napkin", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
  installer.pods_project.targets.each  do |target|
      target.build_configurations.each  do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end
